using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Net;
using System.Text;

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."

namespace INPS.Pensioni.Liquidazione.Service_Reference
{
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0))")]
    public partial class msParallelRunClient
    {
        private const string Config_ApiParallelRunUrl = "ApiParallelRunUrl";
        private string _baseUrl = ConfigurationManager.AppSettings[Config_ApiParallelRunUrl];

        private WebClient _httpClient;

        public msParallelRunClient(WebClient httpClient)
        {
            _httpClient = httpClient;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }

        public bool ReadResponseAsString { get; set; }

        public string TrasferimentoPensione_(ChiavePensioneDTO body)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "")
                      .Append("/trasferimento-pensione");

            _httpClient.BaseAddress = BaseUrl;

            string jsonBody = JsonConvert.SerializeObject(body);

            try
            {
                string result = Encoding.ASCII.GetString(
                    _httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody))
                );

                return result;
            }
            catch (WebException ex)
            {
                if (ex.Response != null)
                {
                    using (var stream = ex.Response.GetResponseStream())
                    using (var reader = new System.IO.StreamReader(stream))
                    {
                        return reader.ReadToEnd();
                    }
                }

                return ex.ToString();
            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
            finally
            {
                _httpClient.Dispose();
            }
        }

        public string TrasferimentoPensione(ChiavePensioneDTO body, Dictionary<string, string> headers)
        {
            var url = BaseUrl.TrimEnd('/') + "/trasferimento-pensione";
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "POST";
            request.ContentType = "application/json";
            request.Accept = "application/json";

            if (headers != null)
            {
                foreach (var header in headers)
                {
                    request.Headers[header.Key] = header.Value;
                }
            }

            string jsonBody = JsonConvert.SerializeObject(body);
            byte[] byteArray = Encoding.UTF8.GetBytes(jsonBody);
            request.ContentLength = byteArray.Length;

            using (var dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            try
            {
                using (var response = (HttpWebResponse)request.GetResponse())
                using (var reader = new StreamReader(response.GetResponseStream()))
                {
                    return reader.ReadToEnd();
                }
            }
            catch (WebException ex)
            {
                if (ex.Response != null)
                {
                    using (var reader = new StreamReader(ex.Response.GetResponseStream()))
                    {
                        return reader.ReadToEnd();
                    }
                }

                return ex.ToString();
            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class ChiavePensioneDTO
        {
            [Newtonsoft.Json.JsonProperty("decCategPens", Required = Newtonsoft.Json.Required.Always)]
            public string DecCategPens { get; set; }

            [Newtonsoft.Json.JsonProperty("codSede", Required = Newtonsoft.Json.Required.Always)]
            public string CodSede { get; set; }

            [Newtonsoft.Json.JsonProperty("numCert", Required = Newtonsoft.Json.Required.Always)]
            public string NumCert { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class EsitoDto
        {
            [Newtonsoft.Json.JsonProperty("esito", Required = Newtonsoft.Json.Required.Always)]
            public string Esito { get; set; }

            [Newtonsoft.Json.JsonProperty("descrizione", Required = Newtonsoft.Json.Required.Always)]
            public string Descrizione { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }
        }
    }
}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore 472
#pragma warning restore 114
#pragma warning restore 108
