//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace INPS.Pensioni.Liquidazione.ServiceReferences.SAI
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PNBTW01HTTPSoapBinding", Namespace = "file://target.files")]
    public partial class PNBTW01Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback PNBTW01OperationOperationCompleted;

        /// <remarks/>
        public PNBTW01Service()
        {
            this.Url = "http://svil.host.inps:8091/cics/services/PNBTW01";
        }

        /// <remarks/>
        public event PNBTW01OperationCompletedEventHandler PNBTW01OperationCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PNBTW01OperationResponse", Namespace = "http://www.PNBTW01O.com/schemas/PNBTW01OInterface")]
        public ProgramInterface1 PNBTW01Operation([System.Xml.Serialization.XmlElementAttribute("PNBTW01Operation", Namespace = "http://www.PNBTW01I.com/schemas/PNBTW01IInterface")] ProgramInterface PNBTW01Operation1)
        {
            object[] results = this.Invoke("PNBTW01Operation", new object[] {
                    PNBTW01Operation1});
            return ((ProgramInterface1)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPNBTW01Operation(ProgramInterface PNBTW01Operation1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("PNBTW01Operation", new object[] {
                    PNBTW01Operation1}, callback, asyncState);
        }

        /// <remarks/>
        public ProgramInterface1 EndPNBTW01Operation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProgramInterface1)(results[0]));
        }

        /// <remarks/>
        public void PNBTW01OperationAsync(ProgramInterface PNBTW01Operation1)
        {
            this.PNBTW01OperationAsync(PNBTW01Operation1, null);
        }

        /// <remarks/>
        public void PNBTW01OperationAsync(ProgramInterface PNBTW01Operation1, object userState)
        {
            if ((this.PNBTW01OperationOperationCompleted == null))
            {
                this.PNBTW01OperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPNBTW01OperationOperationCompleted);
            }
            this.InvokeAsync("PNBTW01Operation", new object[] {
                    PNBTW01Operation1}, this.PNBTW01OperationOperationCompleted, userState);
        }

        private void OnPNBTW01OperationOperationCompleted(object arg)
        {
            if ((this.PNBTW01OperationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PNBTW01OperationCompleted(this, new PNBTW01OperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.PNBTW01I.com/schemas/PNBTW01IInterface")]
    public partial class ProgramInterface
    {

        private ProgramInterfaceGetsai getsaiField;

        /// <remarks/>
        public ProgramInterfaceGetsai getsai
        {
            get
            {
                return this.getsaiField;
            }
            set
            {
                this.getsaiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.PNBTW01I.com/schemas/PNBTW01IInterface")]
    public partial class ProgramInterfaceGetsai
    {

        private ProgramInterfaceGetsaiNbw1_dati_input nbw1_dati_inputField;

        /// <remarks/>
        public ProgramInterfaceGetsaiNbw1_dati_input nbw1_dati_input
        {
            get
            {
                return this.nbw1_dati_inputField;
            }
            set
            {
                this.nbw1_dati_inputField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.PNBTW01I.com/schemas/PNBTW01IInterface")]
    public partial class ProgramInterfaceGetsaiNbw1_dati_input
    {

        private string nbw1i_tipo_ricField;

        private string nbw1i_cod_fiscField;

        private string nbw1i_num_dom_inpsField;

        private string nbw1i_tipo_liqField;

        private string nbw1i_dt_calcoloField;

        private string nbw1i_categoriaField;

        private string nbw1i_nr_certifField;

        private string nbw1i_sedeField;

        /// <remarks/>
        public string nbw1i_tipo_ric
        {
            get
            {
                return this.nbw1i_tipo_ricField;
            }
            set
            {
                this.nbw1i_tipo_ricField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_cod_fisc
        {
            get
            {
                return this.nbw1i_cod_fiscField;
            }
            set
            {
                this.nbw1i_cod_fiscField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_num_dom_inps
        {
            get
            {
                return this.nbw1i_num_dom_inpsField;
            }
            set
            {
                this.nbw1i_num_dom_inpsField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_tipo_liq
        {
            get
            {
                return this.nbw1i_tipo_liqField;
            }
            set
            {
                this.nbw1i_tipo_liqField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_dt_calcolo
        {
            get
            {
                return this.nbw1i_dt_calcoloField;
            }
            set
            {
                this.nbw1i_dt_calcoloField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_categoria
        {
            get
            {
                return this.nbw1i_categoriaField;
            }
            set
            {
                this.nbw1i_categoriaField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_nr_certif
        {
            get
            {
                return this.nbw1i_nr_certifField;
            }
            set
            {
                this.nbw1i_nr_certifField = value;
            }
        }

        /// <remarks/>
        public string nbw1i_sede
        {
            get
            {
                return this.nbw1i_sedeField;
            }
            set
            {
                this.nbw1i_sedeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ProgramInterface", Namespace = "http://www.PNBTW01O.com/schemas/PNBTW01OInterface")]
    public partial class ProgramInterface1
    {

        private ProgramInterfaceGetsao getsaoField;

        /// <remarks/>
        public ProgramInterfaceGetsao getsao
        {
            get
            {
                return this.getsaoField;
            }
            set
            {
                this.getsaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.PNBTW01O.com/schemas/PNBTW01OInterface")]
    public partial class ProgramInterfaceGetsao
    {

        private ProgramInterfaceGetsaoNbw1_dati_output nbw1_dati_outputField;

        /// <remarks/>
        public ProgramInterfaceGetsaoNbw1_dati_output nbw1_dati_output
        {
            get
            {
                return this.nbw1_dati_outputField;
            }
            set
            {
                this.nbw1_dati_outputField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.PNBTW01O.com/schemas/PNBTW01OInterface")]
    public partial class ProgramInterfaceGetsaoNbw1_dati_output
    {

        private string nbw1o_esitoField;

        private string nbw1o_des_erroreField;

        private string nbw1o_cod_tip_domField;

        private string nbw1o_tipo_penField;

        private string nbw1o_dt_decorrenzaField;

        private string nbw1o_dt_rag_reqField;

        private ushort nbw1o_eta_mat_dirField;

        private ushort nbw1o_eta_mat_misField;

        private string nbw1o_qual_prevField;

        private string nbw1o_dt_finestraField;

        private string nbw1o_sistema_calcoloField;

        private uint nbw1o_nr_ctb_misField;

        private uint nbw1o_nr_ctb_dirField;

        private uint nbw1o_tot_ctb_qualField;

        private uint nbw1o_tot_ctb_qual_qnqField;

        private uint nbw1o_tot_ctb_qual_triField;

        private uint nbw1o_nr_ctb_nl222Field;

        private uint nbw1o_nr_ctb_nl155Field;

        private uint nbw1o_nr_ctb_nvvField;

        private string nbw1o_dt_pri_ctbField;

        private ushort nbw1o_aamm_tra_dirField;

        private string nbw1o_rag_prevField;

        private string nbw1o_gru_prevField;

        private string nbw1o_gru_dirField;

        private uint nbw1o_nr_tot_ctbField;

        private uint nbw1o_nr_tot_ctb_obgField;

        private uint nbw1o_nr_ctb_anteField;

        private uint nbw1o_nr_ctb_quoaField;

        private decimal nbw1o_rtb_med_540Field;

        private decimal nbw1o_imp_quaField;

        private uint nbw1o_nr_ctb_postField;

        private uint nbw1o_nr_ctb_quobField;

        private decimal nbw1o_rtb_med_postField;

        private decimal nbw1o_imp_qubField;

        private decimal nbw1o_imp_rtvField;

        private decimal nbw1o_imp_contrField;

        private decimal nbw1o_imp_prtField;

        private decimal nbw1o_mont_cmpField;

        private decimal nbw1o_coeff_trasfField;

        private string nbw1o_ind_ibtField;

        private string nbw1o_deroga1Field;

        private string nbw1o_deroga2Field;

        private string nbw1o_deroga3Field;

        private string nbw1o_deroga4Field;

        private decimal nbw1o_imp_pensField;

        private string nbw1o_dt_fin_assField;

        private string nbw1o_dt_inis_supField;

        private string nbw1o_dt_fin_supField;

        private decimal nbw1o_imp_supField;

        private string nbw1o_tip_liqField;

        private uint nbw1o_num_ctb_enp_anteField;

        private uint nbw1o_num_ctb_inps_anteField;

        private uint nbw1o_num_ctb_est_anteField;

        private uint nbw1o_num_ctb_fig_anteField;

        private uint nbw1o_num_ctb_vv_anteField;

        private uint nbw1o_num_ctb_uff_anteField;

        private uint nbw1o_num_ctb_enp_postField;

        private uint nbw1o_num_ctb_inps_postField;

        private uint nbw1o_num_ctb_est_postField;

        private uint nbw1o_num_ctb_fig_postField;

        private uint nbw1o_num_ctb_vv_postField;

        private uint nbw1o_num_ctb_uff_postField;

        private uint nbw1o_num_ctb_enp_contField;

        private uint nbw1o_num_ctb_inps_contField;

        private uint nbw1o_num_ctb_est_contField;

        private uint nbw1o_num_ctb_fig_contField;

        private uint nbw1o_num_ctb_vv_contField;

        private uint nbw1o_num_ctb_uff_contField;

        private uint nbw1o_num_ctb_post_707Field;

        private decimal nbw1o_imp_qua_707Field;

        private decimal nbw1o_imp_qub_707Field;

        private decimal nbw1o_imp_pens_707Field;

        private string nbw1o_fillerField;

        /// <remarks/>
        public string nbw1o_esito
        {
            get
            {
                return this.nbw1o_esitoField;
            }
            set
            {
                this.nbw1o_esitoField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_des_errore
        {
            get
            {
                return this.nbw1o_des_erroreField;
            }
            set
            {
                this.nbw1o_des_erroreField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_cod_tip_dom
        {
            get
            {
                return this.nbw1o_cod_tip_domField;
            }
            set
            {
                this.nbw1o_cod_tip_domField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_tipo_pen
        {
            get
            {
                return this.nbw1o_tipo_penField;
            }
            set
            {
                this.nbw1o_tipo_penField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_decorrenza
        {
            get
            {
                return this.nbw1o_dt_decorrenzaField;
            }
            set
            {
                this.nbw1o_dt_decorrenzaField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_rag_req
        {
            get
            {
                return this.nbw1o_dt_rag_reqField;
            }
            set
            {
                this.nbw1o_dt_rag_reqField = value;
            }
        }

        /// <remarks/>
        public ushort nbw1o_eta_mat_dir
        {
            get
            {
                return this.nbw1o_eta_mat_dirField;
            }
            set
            {
                this.nbw1o_eta_mat_dirField = value;
            }
        }

        /// <remarks/>
        public ushort nbw1o_eta_mat_mis
        {
            get
            {
                return this.nbw1o_eta_mat_misField;
            }
            set
            {
                this.nbw1o_eta_mat_misField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_qual_prev
        {
            get
            {
                return this.nbw1o_qual_prevField;
            }
            set
            {
                this.nbw1o_qual_prevField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_finestra
        {
            get
            {
                return this.nbw1o_dt_finestraField;
            }
            set
            {
                this.nbw1o_dt_finestraField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_sistema_calcolo
        {
            get
            {
                return this.nbw1o_sistema_calcoloField;
            }
            set
            {
                this.nbw1o_sistema_calcoloField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_mis
        {
            get
            {
                return this.nbw1o_nr_ctb_misField;
            }
            set
            {
                this.nbw1o_nr_ctb_misField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_dir
        {
            get
            {
                return this.nbw1o_nr_ctb_dirField;
            }
            set
            {
                this.nbw1o_nr_ctb_dirField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_tot_ctb_qual
        {
            get
            {
                return this.nbw1o_tot_ctb_qualField;
            }
            set
            {
                this.nbw1o_tot_ctb_qualField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_tot_ctb_qual_qnq
        {
            get
            {
                return this.nbw1o_tot_ctb_qual_qnqField;
            }
            set
            {
                this.nbw1o_tot_ctb_qual_qnqField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_tot_ctb_qual_tri
        {
            get
            {
                return this.nbw1o_tot_ctb_qual_triField;
            }
            set
            {
                this.nbw1o_tot_ctb_qual_triField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_nl222
        {
            get
            {
                return this.nbw1o_nr_ctb_nl222Field;
            }
            set
            {
                this.nbw1o_nr_ctb_nl222Field = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_nl155
        {
            get
            {
                return this.nbw1o_nr_ctb_nl155Field;
            }
            set
            {
                this.nbw1o_nr_ctb_nl155Field = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_nvv
        {
            get
            {
                return this.nbw1o_nr_ctb_nvvField;
            }
            set
            {
                this.nbw1o_nr_ctb_nvvField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_pri_ctb
        {
            get
            {
                return this.nbw1o_dt_pri_ctbField;
            }
            set
            {
                this.nbw1o_dt_pri_ctbField = value;
            }
        }

        /// <remarks/>
        public ushort nbw1o_aamm_tra_dir
        {
            get
            {
                return this.nbw1o_aamm_tra_dirField;
            }
            set
            {
                this.nbw1o_aamm_tra_dirField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_rag_prev
        {
            get
            {
                return this.nbw1o_rag_prevField;
            }
            set
            {
                this.nbw1o_rag_prevField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_gru_prev
        {
            get
            {
                return this.nbw1o_gru_prevField;
            }
            set
            {
                this.nbw1o_gru_prevField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_gru_dir
        {
            get
            {
                return this.nbw1o_gru_dirField;
            }
            set
            {
                this.nbw1o_gru_dirField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_tot_ctb
        {
            get
            {
                return this.nbw1o_nr_tot_ctbField;
            }
            set
            {
                this.nbw1o_nr_tot_ctbField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_tot_ctb_obg
        {
            get
            {
                return this.nbw1o_nr_tot_ctb_obgField;
            }
            set
            {
                this.nbw1o_nr_tot_ctb_obgField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_ante
        {
            get
            {
                return this.nbw1o_nr_ctb_anteField;
            }
            set
            {
                this.nbw1o_nr_ctb_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_quoa
        {
            get
            {
                return this.nbw1o_nr_ctb_quoaField;
            }
            set
            {
                this.nbw1o_nr_ctb_quoaField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_rtb_med_540
        {
            get
            {
                return this.nbw1o_rtb_med_540Field;
            }
            set
            {
                this.nbw1o_rtb_med_540Field = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_qua
        {
            get
            {
                return this.nbw1o_imp_quaField;
            }
            set
            {
                this.nbw1o_imp_quaField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_post
        {
            get
            {
                return this.nbw1o_nr_ctb_postField;
            }
            set
            {
                this.nbw1o_nr_ctb_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_nr_ctb_quob
        {
            get
            {
                return this.nbw1o_nr_ctb_quobField;
            }
            set
            {
                this.nbw1o_nr_ctb_quobField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_rtb_med_post
        {
            get
            {
                return this.nbw1o_rtb_med_postField;
            }
            set
            {
                this.nbw1o_rtb_med_postField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_qub
        {
            get
            {
                return this.nbw1o_imp_qubField;
            }
            set
            {
                this.nbw1o_imp_qubField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_rtv
        {
            get
            {
                return this.nbw1o_imp_rtvField;
            }
            set
            {
                this.nbw1o_imp_rtvField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_contr
        {
            get
            {
                return this.nbw1o_imp_contrField;
            }
            set
            {
                this.nbw1o_imp_contrField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_prt
        {
            get
            {
                return this.nbw1o_imp_prtField;
            }
            set
            {
                this.nbw1o_imp_prtField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_mont_cmp
        {
            get
            {
                return this.nbw1o_mont_cmpField;
            }
            set
            {
                this.nbw1o_mont_cmpField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_coeff_trasf
        {
            get
            {
                return this.nbw1o_coeff_trasfField;
            }
            set
            {
                this.nbw1o_coeff_trasfField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_ind_ibt
        {
            get
            {
                return this.nbw1o_ind_ibtField;
            }
            set
            {
                this.nbw1o_ind_ibtField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_deroga1
        {
            get
            {
                return this.nbw1o_deroga1Field;
            }
            set
            {
                this.nbw1o_deroga1Field = value;
            }
        }

        /// <remarks/>
        public string nbw1o_deroga2
        {
            get
            {
                return this.nbw1o_deroga2Field;
            }
            set
            {
                this.nbw1o_deroga2Field = value;
            }
        }

        /// <remarks/>
        public string nbw1o_deroga3
        {
            get
            {
                return this.nbw1o_deroga3Field;
            }
            set
            {
                this.nbw1o_deroga3Field = value;
            }
        }

        /// <remarks/>
        public string nbw1o_deroga4
        {
            get
            {
                return this.nbw1o_deroga4Field;
            }
            set
            {
                this.nbw1o_deroga4Field = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_pens
        {
            get
            {
                return this.nbw1o_imp_pensField;
            }
            set
            {
                this.nbw1o_imp_pensField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_fin_ass
        {
            get
            {
                return this.nbw1o_dt_fin_assField;
            }
            set
            {
                this.nbw1o_dt_fin_assField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_inis_sup
        {
            get
            {
                return this.nbw1o_dt_inis_supField;
            }
            set
            {
                this.nbw1o_dt_inis_supField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_dt_fin_sup
        {
            get
            {
                return this.nbw1o_dt_fin_supField;
            }
            set
            {
                this.nbw1o_dt_fin_supField = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_sup
        {
            get
            {
                return this.nbw1o_imp_supField;
            }
            set
            {
                this.nbw1o_imp_supField = value;
            }
        }

        /// <remarks/>
        public string nbw1o_tip_liq
        {
            get
            {
                return this.nbw1o_tip_liqField;
            }
            set
            {
                this.nbw1o_tip_liqField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_enp_ante
        {
            get
            {
                return this.nbw1o_num_ctb_enp_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_enp_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_inps_ante
        {
            get
            {
                return this.nbw1o_num_ctb_inps_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_inps_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_est_ante
        {
            get
            {
                return this.nbw1o_num_ctb_est_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_est_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_fig_ante
        {
            get
            {
                return this.nbw1o_num_ctb_fig_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_fig_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_vv_ante
        {
            get
            {
                return this.nbw1o_num_ctb_vv_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_vv_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_uff_ante
        {
            get
            {
                return this.nbw1o_num_ctb_uff_anteField;
            }
            set
            {
                this.nbw1o_num_ctb_uff_anteField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_enp_post
        {
            get
            {
                return this.nbw1o_num_ctb_enp_postField;
            }
            set
            {
                this.nbw1o_num_ctb_enp_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_inps_post
        {
            get
            {
                return this.nbw1o_num_ctb_inps_postField;
            }
            set
            {
                this.nbw1o_num_ctb_inps_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_est_post
        {
            get
            {
                return this.nbw1o_num_ctb_est_postField;
            }
            set
            {
                this.nbw1o_num_ctb_est_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_fig_post
        {
            get
            {
                return this.nbw1o_num_ctb_fig_postField;
            }
            set
            {
                this.nbw1o_num_ctb_fig_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_vv_post
        {
            get
            {
                return this.nbw1o_num_ctb_vv_postField;
            }
            set
            {
                this.nbw1o_num_ctb_vv_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_uff_post
        {
            get
            {
                return this.nbw1o_num_ctb_uff_postField;
            }
            set
            {
                this.nbw1o_num_ctb_uff_postField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_enp_cont
        {
            get
            {
                return this.nbw1o_num_ctb_enp_contField;
            }
            set
            {
                this.nbw1o_num_ctb_enp_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_inps_cont
        {
            get
            {
                return this.nbw1o_num_ctb_inps_contField;
            }
            set
            {
                this.nbw1o_num_ctb_inps_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_est_cont
        {
            get
            {
                return this.nbw1o_num_ctb_est_contField;
            }
            set
            {
                this.nbw1o_num_ctb_est_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_fig_cont
        {
            get
            {
                return this.nbw1o_num_ctb_fig_contField;
            }
            set
            {
                this.nbw1o_num_ctb_fig_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_vv_cont
        {
            get
            {
                return this.nbw1o_num_ctb_vv_contField;
            }
            set
            {
                this.nbw1o_num_ctb_vv_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_uff_cont
        {
            get
            {
                return this.nbw1o_num_ctb_uff_contField;
            }
            set
            {
                this.nbw1o_num_ctb_uff_contField = value;
            }
        }

        /// <remarks/>
        public uint nbw1o_num_ctb_post_707
        {
            get
            {
                return this.nbw1o_num_ctb_post_707Field;
            }
            set
            {
                this.nbw1o_num_ctb_post_707Field = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_qua_707
        {
            get
            {
                return this.nbw1o_imp_qua_707Field;
            }
            set
            {
                this.nbw1o_imp_qua_707Field = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_qub_707
        {
            get
            {
                return this.nbw1o_imp_qub_707Field;
            }
            set
            {
                this.nbw1o_imp_qub_707Field = value;
            }
        }

        /// <remarks/>
        public decimal nbw1o_imp_pens_707
        {
            get
            {
                return this.nbw1o_imp_pens_707Field;
            }
            set
            {
                this.nbw1o_imp_pens_707Field = value;
            }
        }

        /// <remarks/>
        public string nbw1o_filler
        {
            get
            {
                return this.nbw1o_fillerField;
            }
            set
            {
                this.nbw1o_fillerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void PNBTW01OperationCompletedEventHandler(object sender, PNBTW01OperationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PNBTW01OperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PNBTW01OperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ProgramInterface1 Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ProgramInterface1)(this.results[0]));
            }
        }
    }
}