//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace INPS.Pensioni.LiquidazionePensione.View.Web {
    
    
    public partial class CambioStatoDomanda {
        
        /// <summary>
        /// ucAvviso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.UCAvviso ucAvviso;
        
        /// <summary>
        /// VSAggiornaStatoDomanda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary VSAggiornaStatoDomanda;
        
        /// <summary>
        /// ucCambioStatoDomanda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.AltreFunzioni.CambioStatoDomanda.UCCambioStatoDomanda ucCambioStatoDomanda;
    }
}
