//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inps.it/AS/WS/NumerazioneLIPE/", ConfigurationName="SrvAssegnazioneCertificato.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://inps.it/XMLSchema/AssegnazioneCertificato.xsd) does not match the default value (http://inps.it/AS/WS/NumerazioneLIPE/)
        [System.ServiceModel.OperationContractAttribute(Action="http://inps.it/AS/WS/NumerazioneLIPE/AssegnazioneCertificato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoResponse AssegnazioneCertificato(INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd")]
    public partial class richiestaAssegnazioneCertificato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceSedeField;
        
        private string categoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codiceSede {
            get {
                return this.codiceSedeField;
            }
            set {
                this.codiceSedeField = value;
                this.RaisePropertyChanged("codiceSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd")]
    public partial class esitoAssegnazioneCertificato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceRispostaField;
        
        private string certificatoField;
        
        private string descrErroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codiceRisposta {
            get {
                return this.codiceRispostaField;
            }
            set {
                this.codiceRispostaField = value;
                this.RaisePropertyChanged("codiceRisposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string certificato {
            get {
                return this.certificatoField;
            }
            set {
                this.certificatoField = value;
                this.RaisePropertyChanged("certificato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descrErrore {
            get {
                return this.descrErroreField;
            }
            set {
                this.descrErroreField = value;
                this.RaisePropertyChanged("descrErrore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssegnazioneCertificato", WrapperNamespace="http://inps.it/AS/WS/NumerazioneLIPE/", IsWrapped=true)]
    public partial class AssegnazioneCertificatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd")]
        public INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.richiestaAssegnazioneCertificato _richiesta;
        
        public AssegnazioneCertificatoRequest() {
        }
        
        public AssegnazioneCertificatoRequest(INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.richiestaAssegnazioneCertificato _richiesta) {
            this._richiesta = _richiesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssegnazioneCertificatoResponse", WrapperNamespace="http://inps.it/AS/WS/NumerazioneLIPE/", IsWrapped=true)]
    public partial class AssegnazioneCertificatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://inps.it/XMLSchema/AssegnazioneCertificato.xsd")]
        public INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.esitoAssegnazioneCertificato AssegnazioneCertificatoResult;
        
        public AssegnazioneCertificatoResponse() {
        }
        
        public AssegnazioneCertificatoResponse(INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.esitoAssegnazioneCertificato AssegnazioneCertificatoResult) {
            this.AssegnazioneCertificatoResult = AssegnazioneCertificatoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.ServicesSoap>, INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoResponse INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.ServicesSoap.AssegnazioneCertificato(INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoRequest request) {
            return base.Channel.AssegnazioneCertificato(request);
        }
        
        public INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.esitoAssegnazioneCertificato AssegnazioneCertificato(INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.richiestaAssegnazioneCertificato _richiesta) {
            INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoRequest inValue = new INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoRequest();
            inValue._richiesta = _richiesta;
            INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.AssegnazioneCertificatoResponse retVal = ((INPS.Pensioni.Liquidazione.SrvAssegnazioneCertificato.ServicesSoap)(this)).AssegnazioneCertificato(inValue);
            return retVal.AssegnazioneCertificatoResult;
        }
    }
}
