//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws.deploy.inps.it/", ConfigurationName = "SrvNACI.WSSERVIZINACIService")]
    public interface WSSERVIZINACIService
    {

        // CODEGEN: Generating message contract since the operation getStatiIstituzione is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.deploy.inps.it/getStatiIstituzione", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse1 getStatiIstituzione(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneRequest request);

        // CODEGEN: Generating message contract since the operation verificaProceduraEESSI is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.deploy.inps.it/verificaProceduraEESSI", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse1 verificaProceduraEESSI(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIRequest request);

        // CODEGEN: Generating message contract since the operation getDatiNaci is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.deploy.inps.it/getDatiNaci", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse1 getDatiNaci(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class getStatiIstituzione : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloGetStatiIstituzioneRichiesta moduloGetStatiIstituzioneRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloGetStatiIstituzioneRichiesta ModuloGetStatiIstituzioneRichiesta
        {
            get
            {
                return this.moduloGetStatiIstituzioneRichiestaField;
            }
            set
            {
                this.moduloGetStatiIstituzioneRichiestaField = value;
                this.RaisePropertyChanged("ModuloGetStatiIstituzioneRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloGetStatiIstituzioneRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoGetStatiIstituzioneRichiesta datiRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoGetStatiIstituzioneRichiesta DatiRichiesta
        {
            get
            {
                return this.datiRichiestaField;
            }
            set
            {
                this.datiRichiestaField = value;
                this.RaisePropertyChanged("DatiRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoMetadatiServizio : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoNomeServizio nomeServizioField;

        private string mittenteField;

        private long timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoNomeServizio NomeServizio
        {
            get
            {
                return this.nomeServizioField;
            }
            set
            {
                this.nomeServizioField = value;
                this.RaisePropertyChanged("NomeServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Mittente
        {
            get
            {
                return this.mittenteField;
            }
            set
            {
                this.mittenteField = value;
                this.RaisePropertyChanged("Mittente");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public long Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public enum TipoNomeServizio
    {

        /// <remarks/>
        GetStatiIstituzioneService,

        /// <remarks/>
        VerificaProceduraEESSIService,

        /// <remarks/>
        GetDatiNaciService,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoDecisioneItaliana : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codiceField;

        private string descrizioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoStatoCivile : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codiceField;

        private string descrizioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoDatiTitolare : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string cognomeField;

        private string cognomeAcquisitoField;

        private string nomeField;

        private string sessoField;

        private string dataNascitaField;

        private string luogonascitaField;

        private string codiceFiscaleField;

        private string cittadinanzaField;

        private TipoStatoCivile statoCivileField;

        private string dataDecessoField;

        private string provinciaNascitaField;

        private string statoNascitaField;

        private System.Nullable<bool> natoEsteroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public string Cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
                this.RaisePropertyChanged("Cognome");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string CognomeAcquisito
        {
            get
            {
                return this.cognomeAcquisitoField;
            }
            set
            {
                this.cognomeAcquisitoField = value;
                this.RaisePropertyChanged("CognomeAcquisito");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        public string Sesso
        {
            get
            {
                return this.sessoField;
            }
            set
            {
                this.sessoField = value;
                this.RaisePropertyChanged("Sesso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 4)]
        public string DataNascita
        {
            get
            {
                return this.dataNascitaField;
            }
            set
            {
                this.dataNascitaField = value;
                this.RaisePropertyChanged("DataNascita");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 5)]
        public string Luogonascita
        {
            get
            {
                return this.luogonascitaField;
            }
            set
            {
                this.luogonascitaField = value;
                this.RaisePropertyChanged("Luogonascita");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
                this.RaisePropertyChanged("CodiceFiscale");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 7)]
        public string Cittadinanza
        {
            get
            {
                return this.cittadinanzaField;
            }
            set
            {
                this.cittadinanzaField = value;
                this.RaisePropertyChanged("Cittadinanza");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 8)]
        public TipoStatoCivile StatoCivile
        {
            get
            {
                return this.statoCivileField;
            }
            set
            {
                this.statoCivileField = value;
                this.RaisePropertyChanged("StatoCivile");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 9)]
        public string DataDecesso
        {
            get
            {
                return this.dataDecessoField;
            }
            set
            {
                this.dataDecessoField = value;
                this.RaisePropertyChanged("DataDecesso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 10)]
        public string ProvinciaNascita
        {
            get
            {
                return this.provinciaNascitaField;
            }
            set
            {
                this.provinciaNascitaField = value;
                this.RaisePropertyChanged("ProvinciaNascita");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 11)]
        public string StatoNascita
        {
            get
            {
                return this.statoNascitaField;
            }
            set
            {
                this.statoNascitaField = value;
                this.RaisePropertyChanged("StatoNascita");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 12)]
        public System.Nullable<bool> NatoEstero
        {
            get
            {
                return this.natoEsteroField;
            }
            set
            {
                this.natoEsteroField = value;
                this.RaisePropertyChanged("NatoEstero");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoGetDatiNaciRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMessaggio messaggioField;

        private string cittadinanzaField;

        private string cittadinanzaDcField;

        private string cittadinanzaISOField;

        private string cittadinanzaDcISOField;

        private string cittadinanzaArca2Field;

        private string cittadinanzaDcArca2Field;

        private string attivita107Field;

        private TipoStato[] statiField;

        private TipoDatiTitolare datiTitolareField;

        private string dataPresentazioneDomandaField;

        private TipoDecisioneItaliana decisioneItalianaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMessaggio Messaggio
        {
            get
            {
                return this.messaggioField;
            }
            set
            {
                this.messaggioField = value;
                this.RaisePropertyChanged("Messaggio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string Cittadinanza
        {
            get
            {
                return this.cittadinanzaField;
            }
            set
            {
                this.cittadinanzaField = value;
                this.RaisePropertyChanged("Cittadinanza");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string CittadinanzaDc
        {
            get
            {
                return this.cittadinanzaDcField;
            }
            set
            {
                this.cittadinanzaDcField = value;
                this.RaisePropertyChanged("CittadinanzaDc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        public string CittadinanzaISO
        {
            get
            {
                return this.cittadinanzaISOField;
            }
            set
            {
                this.cittadinanzaISOField = value;
                this.RaisePropertyChanged("CittadinanzaISO");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 4)]
        public string CittadinanzaDcISO
        {
            get
            {
                return this.cittadinanzaDcISOField;
            }
            set
            {
                this.cittadinanzaDcISOField = value;
                this.RaisePropertyChanged("CittadinanzaDcISO");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 5)]
        public string CittadinanzaArca2
        {
            get
            {
                return this.cittadinanzaArca2Field;
            }
            set
            {
                this.cittadinanzaArca2Field = value;
                this.RaisePropertyChanged("CittadinanzaArca2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 6)]
        public string CittadinanzaDcArca2
        {
            get
            {
                return this.cittadinanzaDcArca2Field;
            }
            set
            {
                this.cittadinanzaDcArca2Field = value;
                this.RaisePropertyChanged("CittadinanzaDcArca2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 7)]
        public string Attivita107
        {
            get
            {
                return this.attivita107Field;
            }
            set
            {
                this.attivita107Field = value;
                this.RaisePropertyChanged("Attivita107");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Stato", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public TipoStato[] Stati
        {
            get
            {
                return this.statiField;
            }
            set
            {
                this.statiField = value;
                this.RaisePropertyChanged("Stati");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public TipoDatiTitolare DatiTitolare
        {
            get
            {
                return this.datiTitolareField;
            }
            set
            {
                this.datiTitolareField = value;
                this.RaisePropertyChanged("DatiTitolare");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 10)]
        public string DataPresentazioneDomanda
        {
            get
            {
                return this.dataPresentazioneDomandaField;
            }
            set
            {
                this.dataPresentazioneDomandaField = value;
                this.RaisePropertyChanged("DataPresentazioneDomanda");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 11)]
        public TipoDecisioneItaliana DecisioneItaliana
        {
            get
            {
                return this.decisioneItalianaField;
            }
            set
            {
                this.decisioneItalianaField = value;
                this.RaisePropertyChanged("DecisioneItaliana");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoMessaggio : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int codiceField;

        private string descrizioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoStato : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codiceStatoField;

        private string codiceIstituzioneField;

        private string matricolaField;

        private string provvedimentoEsteroField;

        private string dataProvvedimentoEsteroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public string CodiceStato
        {
            get
            {
                return this.codiceStatoField;
            }
            set
            {
                this.codiceStatoField = value;
                this.RaisePropertyChanged("CodiceStato");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string CodiceIstituzione
        {
            get
            {
                return this.codiceIstituzioneField;
            }
            set
            {
                this.codiceIstituzioneField = value;
                this.RaisePropertyChanged("CodiceIstituzione");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string Matricola
        {
            get
            {
                return this.matricolaField;
            }
            set
            {
                this.matricolaField = value;
                this.RaisePropertyChanged("Matricola");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        public string ProvvedimentoEstero
        {
            get
            {
                return this.provvedimentoEsteroField;
            }
            set
            {
                this.provvedimentoEsteroField = value;
                this.RaisePropertyChanged("ProvvedimentoEstero");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 4)]
        public string DataProvvedimentoEstero
        {
            get
            {
                return this.dataProvvedimentoEsteroField;
            }
            set
            {
                this.dataProvvedimentoEsteroField = value;
                this.RaisePropertyChanged("DataProvvedimentoEstero");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloGetDatiNaciRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoGetDatiNaciRisposta datiRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoGetDatiNaciRisposta DatiRisposta
        {
            get
            {
                return this.datiRispostaField;
            }
            set
            {
                this.datiRispostaField = value;
                this.RaisePropertyChanged("DatiRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoGetDatiNaciRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroDomusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string NumeroDomus
        {
            get
            {
                return this.numeroDomusField;
            }
            set
            {
                this.numeroDomusField = value;
                this.RaisePropertyChanged("NumeroDomus");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloGetDatiNaciRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoGetDatiNaciRichiesta datiRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoGetDatiNaciRichiesta DatiRichiesta
        {
            get
            {
                return this.datiRichiestaField;
            }
            set
            {
                this.datiRichiestaField = value;
                this.RaisePropertyChanged("DatiRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoVerificaProceduraEESSIRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMessaggio messaggioField;

        private System.Nullable<bool> presenteInProcedureEESSIField;

        private bool presenteInProcedureEESSIFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMessaggio Messaggio
        {
            get
            {
                return this.messaggioField;
            }
            set
            {
                this.messaggioField = value;
                this.RaisePropertyChanged("Messaggio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public System.Nullable<bool> PresenteInProcedureEESSI
        {
            get
            {
                return this.presenteInProcedureEESSIField;
            }
            set
            {
                this.presenteInProcedureEESSIField = value;
                this.RaisePropertyChanged("PresenteInProcedureEESSI");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PresenteInProcedureEESSISpecified
        {
            get
            {
                return this.presenteInProcedureEESSIFieldSpecified;
            }
            set
            {
                this.presenteInProcedureEESSIFieldSpecified = value;
                this.RaisePropertyChanged("PresenteInProcedureEESSISpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloVerificaProceduraEESSIRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoVerificaProceduraEESSIRisposta datiRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoVerificaProceduraEESSIRisposta DatiRisposta
        {
            get
            {
                return this.datiRispostaField;
            }
            set
            {
                this.datiRispostaField = value;
                this.RaisePropertyChanged("DatiRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoVerificaProceduraEESSIRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroDomusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string NumeroDomus
        {
            get
            {
                return this.numeroDomusField;
            }
            set
            {
                this.numeroDomusField = value;
                this.RaisePropertyChanged("NumeroDomus");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloVerificaProceduraEESSIRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoVerificaProceduraEESSIRichiesta datiRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoVerificaProceduraEESSIRichiesta DatiRichiesta
        {
            get
            {
                return this.datiRichiestaField;
            }
            set
            {
                this.datiRichiestaField = value;
                this.RaisePropertyChanged("DatiRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoGetStatiIstituzioneRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMessaggio messaggioField;

        private string cittadinanzaField;

        private string cittadinanzaDcField;

        private string attivita107Field;

        private TipoStato[] statiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMessaggio Messaggio
        {
            get
            {
                return this.messaggioField;
            }
            set
            {
                this.messaggioField = value;
                this.RaisePropertyChanged("Messaggio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string Cittadinanza
        {
            get
            {
                return this.cittadinanzaField;
            }
            set
            {
                this.cittadinanzaField = value;
                this.RaisePropertyChanged("Cittadinanza");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string CittadinanzaDc
        {
            get
            {
                return this.cittadinanzaDcField;
            }
            set
            {
                this.cittadinanzaDcField = value;
                this.RaisePropertyChanged("CittadinanzaDc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        public string Attivita107
        {
            get
            {
                return this.attivita107Field;
            }
            set
            {
                this.attivita107Field = value;
                this.RaisePropertyChanged("Attivita107");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Stato", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public TipoStato[] Stati
        {
            get
            {
                return this.statiField;
            }
            set
            {
                this.statiField = value;
                this.RaisePropertyChanged("Stati");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoModuloGetStatiIstituzioneRisposta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoMetadatiServizio metadatiServizioField;

        private TipoGetStatiIstituzioneRisposta datiRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoMetadatiServizio MetadatiServizio
        {
            get
            {
                return this.metadatiServizioField;
            }
            set
            {
                this.metadatiServizioField = value;
                this.RaisePropertyChanged("MetadatiServizio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public TipoGetStatiIstituzioneRisposta DatiRisposta
        {
            get
            {
                return this.datiRispostaField;
            }
            set
            {
                this.datiRispostaField = value;
                this.RaisePropertyChanged("DatiRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.deploy.inps.it/")]
    public partial class TipoGetStatiIstituzioneRichiesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroDomusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string NumeroDomus
        {
            get
            {
                return this.numeroDomusField;
            }
            set
            {
                this.numeroDomusField = value;
                this.RaisePropertyChanged("NumeroDomus");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class getStatiIstituzioneResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloGetStatiIstituzioneRisposta moduloGetStatiIstituzioneRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloGetStatiIstituzioneRisposta ModuloGetStatiIstituzioneRisposta
        {
            get
            {
                return this.moduloGetStatiIstituzioneRispostaField;
            }
            set
            {
                this.moduloGetStatiIstituzioneRispostaField = value;
                this.RaisePropertyChanged("ModuloGetStatiIstituzioneRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getStatiIstituzioneRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzione getStatiIstituzione;

        public getStatiIstituzioneRequest()
        {
        }

        public getStatiIstituzioneRequest(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzione getStatiIstituzione)
        {
            this.getStatiIstituzione = getStatiIstituzione;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getStatiIstituzioneResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse getStatiIstituzioneResponse;

        public getStatiIstituzioneResponse1()
        {
        }

        public getStatiIstituzioneResponse1(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse getStatiIstituzioneResponse)
        {
            this.getStatiIstituzioneResponse = getStatiIstituzioneResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class verificaProceduraEESSI : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloVerificaProceduraEESSIRichiesta moduloVerificaProceduraEESSIRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloVerificaProceduraEESSIRichiesta ModuloVerificaProceduraEESSIRichiesta
        {
            get
            {
                return this.moduloVerificaProceduraEESSIRichiestaField;
            }
            set
            {
                this.moduloVerificaProceduraEESSIRichiestaField = value;
                this.RaisePropertyChanged("ModuloVerificaProceduraEESSIRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class verificaProceduraEESSIResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloVerificaProceduraEESSIRisposta moduloVerificaProceduraEESSIRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloVerificaProceduraEESSIRisposta ModuloVerificaProceduraEESSIRisposta
        {
            get
            {
                return this.moduloVerificaProceduraEESSIRispostaField;
            }
            set
            {
                this.moduloVerificaProceduraEESSIRispostaField = value;
                this.RaisePropertyChanged("ModuloVerificaProceduraEESSIRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class verificaProceduraEESSIRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSI verificaProceduraEESSI;

        public verificaProceduraEESSIRequest()
        {
        }

        public verificaProceduraEESSIRequest(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSI verificaProceduraEESSI)
        {
            this.verificaProceduraEESSI = verificaProceduraEESSI;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class verificaProceduraEESSIResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse verificaProceduraEESSIResponse;

        public verificaProceduraEESSIResponse1()
        {
        }

        public verificaProceduraEESSIResponse1(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse verificaProceduraEESSIResponse)
        {
            this.verificaProceduraEESSIResponse = verificaProceduraEESSIResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class getDatiNaci : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloGetDatiNaciRichiesta moduloGetDatiNaciRichiestaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloGetDatiNaciRichiesta ModuloGetDatiNaciRichiesta
        {
            get
            {
                return this.moduloGetDatiNaciRichiestaField;
            }
            set
            {
                this.moduloGetDatiNaciRichiestaField = value;
                this.RaisePropertyChanged("ModuloGetDatiNaciRichiesta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ws.deploy.inps.it/")]
    public partial class getDatiNaciResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private TipoModuloGetDatiNaciRisposta moduloGetDatiNaciRispostaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TipoModuloGetDatiNaciRisposta ModuloGetDatiNaciRisposta
        {
            get
            {
                return this.moduloGetDatiNaciRispostaField;
            }
            set
            {
                this.moduloGetDatiNaciRispostaField = value;
                this.RaisePropertyChanged("ModuloGetDatiNaciRisposta");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getDatiNaciRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaci getDatiNaci;

        public getDatiNaciRequest()
        {
        }

        public getDatiNaciRequest(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaci getDatiNaci)
        {
            this.getDatiNaci = getDatiNaci;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getDatiNaciResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ws.deploy.inps.it/", Order = 0)]
        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse getDatiNaciResponse;

        public getDatiNaciResponse1()
        {
        }

        public getDatiNaciResponse1(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse getDatiNaciResponse)
        {
            this.getDatiNaciResponse = getDatiNaciResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSERVIZINACIServiceChannel : INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSERVIZINACIServiceClient : System.ServiceModel.ClientBase<INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService>, INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService
    {

        public WSSERVIZINACIServiceClient()
        {
        }

        public WSSERVIZINACIServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WSSERVIZINACIServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WSSERVIZINACIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WSSERVIZINACIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse1 INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService.getStatiIstituzione(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneRequest request)
        {
            return base.Channel.getStatiIstituzione(request);
        }

        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse getStatiIstituzione(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzione getStatiIstituzione1)
        {
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneRequest inValue = new INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneRequest();
            inValue.getStatiIstituzione = getStatiIstituzione1;
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getStatiIstituzioneResponse1 retVal = ((INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService)(this)).getStatiIstituzione(inValue);
            return retVal.getStatiIstituzioneResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse1 INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService.verificaProceduraEESSI(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIRequest request)
        {
            return base.Channel.verificaProceduraEESSI(request);
        }

        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse verificaProceduraEESSI(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSI verificaProceduraEESSI1)
        {
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIRequest inValue = new INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIRequest();
            inValue.verificaProceduraEESSI = verificaProceduraEESSI1;
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.verificaProceduraEESSIResponse1 retVal = ((INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService)(this)).verificaProceduraEESSI(inValue);
            return retVal.verificaProceduraEESSIResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse1 INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService.getDatiNaci(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciRequest request)
        {
            return base.Channel.getDatiNaci(request);
        }

        public INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse getDatiNaci(INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaci getDatiNaci1)
        {
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciRequest inValue = new INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciRequest();
            inValue.getDatiNaci = getDatiNaci1;
            INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.getDatiNaciResponse1 retVal = ((INPS.Pensioni.LiquidazioneCi.ServiceReferences.NACI.WSSERVIZINACIService)(this)).getDatiNaci(inValue);
            return retVal.getDatiNaciResponse;
        }
    }
}
