using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."

namespace INPS.Pensioni.LiquidazioneAgo.Data
{
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0))")]
    public partial class msCCQualityDataCheckerClient
    {
        private const string Config_ApiCCQualityDataCheckerUrl = "ApiCCQualityDataCheckerUrl";
        private string _baseUrl = ConfigurationManager.AppSettings[Config_ApiCCQualityDataCheckerUrl];
        private WebClient _httpClient;

        public msCCQualityDataCheckerClient(WebClient httpClient)
        {
            _httpClient = httpClient;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }

        public string Result(ResultOfCalcoloRequestDTO body, string authorization)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/asis/result");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }

        public string DiffDetailAsync(DiffDetailRequestDto body, string authorization)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/asis/diffDetail");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }

        public string Ping(DiffDetailRequestDto body, string authorization)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/ping");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }

        public string FaultAsync(InsertInvFaultRequestDTO body, string authorization)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/new/fault");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }

        public string Mainframe_(OutcomeRequestDTO body)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/monitoring/outcome-summary/mainframe");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }
        public ResponseDTO Mainframe(OutcomeRequestDTO body, Dictionary<string, string> headers)
        {
            var url = BaseUrl.TrimEnd('/') + "/monitoring/outcome-summary/mainframe";
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "POST";
            request.ContentType = "application/json";
            request.Accept = "application/json";

            foreach (var header in headers)
            {
                request.Headers.Add(header.Key, header.Value);
            }

            string jsonBody = JsonConvert.SerializeObject(body);
            byte[] byteArray = Encoding.UTF8.GetBytes(jsonBody);
            request.ContentLength = byteArray.Length;

            using (var dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            using (var response = (HttpWebResponse)request.GetResponse())
            using (var reader = new StreamReader(response.GetResponseStream()))
            {
                string result = reader.ReadToEnd();
                return JsonConvert.DeserializeObject<ResponseDTO>(result);
            }
        }

        public string Abaco_(FaultOutcomeRequestDTO body)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/monitoring/invocation-fault/abaco");
            _httpClient.BaseAddress = BaseUrl;
            string jsonBody = JsonConvert.SerializeObject(body);
            string result = Encoding.ASCII.GetString(_httpClient.UploadData(urlBuilder_.ToString(), "POST", Encoding.Default.GetBytes(jsonBody)));
            _httpClient.Dispose();

            //ResponseDTO output = JsonConvert.DeserializeObject<ResponseDTO>(result);

            return result;
        }

        public ResponseDTO Abaco(FaultOutcomeRequestDTO body, Dictionary<string, string> headers)
        {
            var url = BaseUrl.TrimEnd('/') + "/monitoring/invocation-fault/abaco";
            var request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "POST";
            request.ContentType = "application/json";
            request.Accept = "application/json";

            foreach (var header in headers)
            {
                request.Headers.Add(header.Key, header.Value);
            }

            string jsonBody = JsonConvert.SerializeObject(body);
            byte[] byteArray = Encoding.UTF8.GetBytes(jsonBody);
            request.ContentLength = byteArray.Length;

            using (var dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            using (var response = (HttpWebResponse)request.GetResponse())
            using (var reader = new StreamReader(response.GetResponseStream()))
            {
                string result = reader.ReadToEnd();
                return JsonConvert.DeserializeObject<ResponseDTO>(result);
            }
        }

        public bool ReadResponseAsString { get; set; }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class InsertInvFaultRequestDTO
        {
            [Newtonsoft.Json.JsonProperty("codUtente", Required = Newtonsoft.Json.Required.Always)]

            public string CodUtente { get; set; }

            [Newtonsoft.Json.JsonProperty("numDomanda", Required = Newtonsoft.Json.Required.Always)]
            public int NumDomanda { get; set; }

            [Newtonsoft.Json.JsonProperty("codCategoria", Required = Newtonsoft.Json.Required.Always)]

            public string CodCategoria { get; set; }

            [Newtonsoft.Json.JsonProperty("codSede", Required = Newtonsoft.Json.Required.Always)]

            public string CodSede { get; set; }

            [Newtonsoft.Json.JsonProperty("codCertificato", Required = Newtonsoft.Json.Required.Always)]

            public string CodCertificato { get; set; }

            [Newtonsoft.Json.JsonProperty("codFiscale", Required = Newtonsoft.Json.Required.Always)]

            public string CodFiscale { get; set; }

            [Newtonsoft.Json.JsonProperty("codGruppo", Required = Newtonsoft.Json.Required.Always)]

            public string CodGruppo { get; set; }

            [Newtonsoft.Json.JsonProperty("codProdotto", Required = Newtonsoft.Json.Required.Always)]

            public string CodProdotto { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipo", Required = Newtonsoft.Json.Required.Always)]

            public string CodTipo { get; set; }

            [Newtonsoft.Json.JsonProperty("codGestione", Required = Newtonsoft.Json.Required.Always)]

            public string CodGestione { get; set; }

            [Newtonsoft.Json.JsonProperty("codFondo", Required = Newtonsoft.Json.Required.Always)]

            public string CodFondo { get; set; }

            [Newtonsoft.Json.JsonProperty("codIndconvint", Required = Newtonsoft.Json.Required.Always)]

            public string CodIndconvint { get; set; }

            [Newtonsoft.Json.JsonProperty("descFase", Required = Newtonsoft.Json.Required.Always)]

            public string DescFase { get; set; }

            [Newtonsoft.Json.JsonProperty("tipoRichiesta", Required = Newtonsoft.Json.Required.Always)]

            public string TipoRichiesta { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInizioAsIs", Required = Newtonsoft.Json.Required.Always)]

            public System.DateTimeOffset DataInizioAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("dataFineAsIs", Required = Newtonsoft.Json.Required.Always)]

            public System.DateTimeOffset DataFineAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("codEsitoAsIs", Required = Newtonsoft.Json.Required.Always)]

            public string CodEsitoAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoAsIs", Required = Newtonsoft.Json.Required.Always)]

            public string DescrEsitoAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("codEsitoNew", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodEsitoNew { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoNew", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrEsitoNew { get; set; }

            [Newtonsoft.Json.JsonProperty("bodyResponse", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string BodyResponse { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class ResultOfCalcoloRequestDTO
        {
            [Newtonsoft.Json.JsonProperty("codUtente", Required = Newtonsoft.Json.Required.Always)]

            public string CodUtente { get; set; }

            [Newtonsoft.Json.JsonProperty("transactionId", Required = Newtonsoft.Json.Required.Always)]

            public string TransactionId { get; set; }

            [Newtonsoft.Json.JsonProperty("numDomanda", Required = Newtonsoft.Json.Required.Always)]
            public long NumDomanda { get; set; }

            [Newtonsoft.Json.JsonProperty("chiavePensione", Required = Newtonsoft.Json.Required.Always)]

            public string ChiavePensione { get; set; }

            [Newtonsoft.Json.JsonProperty("codFiscale", Required = Newtonsoft.Json.Required.Always)]

            public string CodFiscale { get; set; }

            [Newtonsoft.Json.JsonProperty("codGruppo", Required = Newtonsoft.Json.Required.Always)]

            public string CodGruppo { get; set; }

            [Newtonsoft.Json.JsonProperty("codProdotto", Required = Newtonsoft.Json.Required.Always)]

            public string CodProdotto { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipo", Required = Newtonsoft.Json.Required.Always)]

            public string CodTipo { get; set; }

            [Newtonsoft.Json.JsonProperty("codGestione", Required = Newtonsoft.Json.Required.Always)]

            public string CodGestione { get; set; }

            [Newtonsoft.Json.JsonProperty("codFondo", Required = Newtonsoft.Json.Required.Always)]

            public string CodFondo { get; set; }

            [Newtonsoft.Json.JsonProperty("indConVint", Required = Newtonsoft.Json.Required.Always)]

            public string IndConVint { get; set; }

            [Newtonsoft.Json.JsonProperty("descFase", Required = Newtonsoft.Json.Required.Always)]

            public string DescFase { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipoRichiesta", Required = Newtonsoft.Json.Required.Always)]

            public string CodTipoRichiesta { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInizioAsIs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public System.DateTimeOffset DataInizioAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("dataFineAsIs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public System.DateTimeOffset DataFineAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("codEsitoAsIs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodEsitoAsIs { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoAsIs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrEsitoAsIs { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class DiffDetailRequestDto
        {
            [Newtonsoft.Json.JsonProperty("codUtente", Required = Newtonsoft.Json.Required.Always)]

            public string CodUtente { get; set; }

            [Newtonsoft.Json.JsonProperty("transactionId", Required = Newtonsoft.Json.Required.Always)]

            public string TransactionId { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipologia", Required = Newtonsoft.Json.Required.Always)]

            public string CodTipologia { get; set; }

            [Newtonsoft.Json.JsonProperty("markdownContent", Required = Newtonsoft.Json.Required.Always)]

            public string MarkdownContent { get; set; }

            [Newtonsoft.Json.JsonProperty("codStato", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodStato { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }

        public partial class OutcomeRequestDTO
        {
            [Newtonsoft.Json.JsonProperty("transactionId", Required = Newtonsoft.Json.Required.Always)]
            public string TransactionId { get; set; }

            [Newtonsoft.Json.JsonProperty("numDomanda", Required = Newtonsoft.Json.Required.Always)]
            public long NumDomanda { get; set; }

            [Newtonsoft.Json.JsonProperty("codCategoria", Required = Newtonsoft.Json.Required.Always)]
            public string CodCategoria { get; set; }

            [Newtonsoft.Json.JsonProperty("codSede", Required = Newtonsoft.Json.Required.Always)]
            public string CodSede { get; set; }

            [Newtonsoft.Json.JsonProperty("codCertificato", Required = Newtonsoft.Json.Required.Always)]
            public string CodCertificato { get; set; }

            [Newtonsoft.Json.JsonProperty("codFiscale", Required = Newtonsoft.Json.Required.Always)]
            public string CodFiscale { get; set; }

            [Newtonsoft.Json.JsonProperty("codGruppo", Required = Newtonsoft.Json.Required.Always)]
            public string CodGruppo { get; set; }

            [Newtonsoft.Json.JsonProperty("codProdotto", Required = Newtonsoft.Json.Required.Always)]
            public string CodProdotto { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipo", Required = Newtonsoft.Json.Required.Always)]
            public string CodTipo { get; set; }

            [Newtonsoft.Json.JsonProperty("codGestione", Required = Newtonsoft.Json.Required.Always)]
            public string CodGestione { get; set; }

            [Newtonsoft.Json.JsonProperty("codFondo", Required = Newtonsoft.Json.Required.Always)]
            public string CodFondo { get; set; }

            [Newtonsoft.Json.JsonProperty("codIndconvint", Required = Newtonsoft.Json.Required.Always)]
            public string CodIndconvint { get; set; }

            [Newtonsoft.Json.JsonProperty("descFase", Required = Newtonsoft.Json.Required.Always)]
            public string DescFase { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipoRichiesta", Required = Newtonsoft.Json.Required.Always)]
            public string CodTipoRichiesta { get; set; }

            [Newtonsoft.Json.JsonProperty("bodyRequest", Required = Newtonsoft.Json.Required.Always)]
            public string BodyRequest { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInvocazioneAbaco", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataInvocazioneAbaco { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInizioMF", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataInizioMF { get; set; }

            [Newtonsoft.Json.JsonProperty("dataFineMF", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataFineMF { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoMF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrEsitoMF { get; set; }

            [Newtonsoft.Json.JsonProperty("codiceErroreMF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodiceErroreMF { get; set; }

            [Newtonsoft.Json.JsonProperty("descrizioneErroreMF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrizioneErroreMF { get; set; }

            [Newtonsoft.Json.JsonProperty("codUtente", Required = Newtonsoft.Json.Required.Always)]
            public string CodUtente { get; set; }

            [Newtonsoft.Json.JsonProperty("codCategoriaPensione", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodCategoriaPensione { get; set; }

            [Newtonsoft.Json.JsonProperty("descCategoriaPensione", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescCategoriaPensione { get; set; }

            [Newtonsoft.Json.JsonProperty("flowCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string FlowCode { get; set; }

            [Newtonsoft.Json.JsonProperty("nomeTupla", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string NomeTupla { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }

        public partial class FaultOutcomeRequestDTO
        {
            [Newtonsoft.Json.JsonProperty("numDomanda", Required = Newtonsoft.Json.Required.Always)]
            public long NumDomanda { get; set; }

            [Newtonsoft.Json.JsonProperty("codCategoria", Required = Newtonsoft.Json.Required.Always)]
            public string CodCategoria { get; set; }

            [Newtonsoft.Json.JsonProperty("codSede", Required = Newtonsoft.Json.Required.Always)]
            public string CodSede { get; set; }

            [Newtonsoft.Json.JsonProperty("codCertificato", Required = Newtonsoft.Json.Required.Always)]
            public string CodCertificato { get; set; }

            [Newtonsoft.Json.JsonProperty("codFiscale", Required = Newtonsoft.Json.Required.Always)]
            public string CodFiscale { get; set; }

            [Newtonsoft.Json.JsonProperty("codGruppo", Required = Newtonsoft.Json.Required.Always)]
            public string CodGruppo { get; set; }

            [Newtonsoft.Json.JsonProperty("codProdotto", Required = Newtonsoft.Json.Required.Always)]
            public string CodProdotto { get; set; }

            [Newtonsoft.Json.JsonProperty("codTipo", Required = Newtonsoft.Json.Required.Always)]
            public string CodTipo { get; set; }

            [Newtonsoft.Json.JsonProperty("codGestione", Required = Newtonsoft.Json.Required.Always)]
            public string CodGestione { get; set; }

            [Newtonsoft.Json.JsonProperty("codFondo", Required = Newtonsoft.Json.Required.Always)]
            public string CodFondo { get; set; }

            [Newtonsoft.Json.JsonProperty("codIndconvint", Required = Newtonsoft.Json.Required.Always)]
            public string CodIndconvint { get; set; }

            [Newtonsoft.Json.JsonProperty("descFase", Required = Newtonsoft.Json.Required.Always)]
            public string DescFase { get; set; }

            [Newtonsoft.Json.JsonProperty("tipoRichiesta", Required = Newtonsoft.Json.Required.Always)]
            public string TipoRichiesta { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInizioMF", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataInizioMF { get; set; }

            [Newtonsoft.Json.JsonProperty("dataFineMF", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataFineMF { get; set; }

            [Newtonsoft.Json.JsonProperty("dataInvocazioneAbaco", Required = Newtonsoft.Json.Required.Always)]
            public System.DateTimeOffset DataInvocazioneAbaco { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoMF", Required = Newtonsoft.Json.Required.Always)]
            public string DescrEsitoMF { get; set; }

            [Newtonsoft.Json.JsonProperty("codiceErroreMF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodiceErroreMF { get; set; }

            [Newtonsoft.Json.JsonProperty("descrizioneErroreMF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrizioneErroreMF { get; set; }

            [Newtonsoft.Json.JsonProperty("descrEsitoAbaco", Required = Newtonsoft.Json.Required.Always)]
            public string DescrEsitoAbaco { get; set; }

            [Newtonsoft.Json.JsonProperty("codiceErroreAbaco", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string CodiceErroreAbaco { get; set; }

            [Newtonsoft.Json.JsonProperty("descrizioneErroreAbaco", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string DescrizioneErroreAbaco { get; set; }

            [Newtonsoft.Json.JsonProperty("bodyRequest", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string BodyRequest { get; set; }

            [Newtonsoft.Json.JsonProperty("bodyResponse", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string BodyResponse { get; set; }

            [Newtonsoft.Json.JsonProperty("codUtente", Required = Newtonsoft.Json.Required.Always)]
            public string CodUtente { get; set; }

            [Newtonsoft.Json.JsonProperty("codCategoriaPensione", Required = Newtonsoft.Json.Required.Always)]
            public string CodCategoriaPensione { get; set; }

            [Newtonsoft.Json.JsonProperty("descCategoriaPensione", Required = Newtonsoft.Json.Required.Always)]
            public string DescCategoriaPensione { get; set; }

            [Newtonsoft.Json.JsonProperty("flowCode", Required = Newtonsoft.Json.Required.Always)]
            public string FlowCode { get; set; }

            [Newtonsoft.Json.JsonProperty("nomeTupla", Required = Newtonsoft.Json.Required.Always)]
            public string NomeTupla { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }

        [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
        public partial class ResponseDTO
        {
            [Newtonsoft.Json.JsonProperty("transactionId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string TransactionId { get; set; }

            [Newtonsoft.Json.JsonProperty("errorMessage", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
            public string ErrorMessage { get; set; }

            private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

            [Newtonsoft.Json.JsonExtensionData]
            public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
            {
                get { return _additionalProperties; }
                set { _additionalProperties = value; }
            }


        }


    }

}
#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore 472
#pragma warning restore 114
#pragma warning restore 108