//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace INPS.Pensioni.LiquidazionePensione.View.Web {
    
    
    public partial class SindacatoPatronato {
        
        /// <summary>
        /// ucAvviso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.UCAvviso ucAvviso;
        
        /// <summary>
        /// hdnSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnSelected;
        
        /// <summary>
        /// validateSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary validateSummary;
        
        /// <summary>
        /// pnlSindacatoPatronato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSindacatoPatronato;
        
        /// <summary>
        /// ucInfoLiquidazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.UCInfo ucInfoLiquidazione;
        
        /// <summary>
        /// pnlTabSindacato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTabSindacato;
        
        /// <summary>
        /// imgSindacato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgSindacato;
        
        /// <summary>
        /// pnlTabPatronato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTabPatronato;
        
        /// <summary>
        /// imgPatronato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgPatronato;
        
        /// <summary>
        /// ucSindacato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.SindacatoPatronato.UCSindacato ucSindacato;
        
        /// <summary>
        /// ucPatronato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::INPS.Pensioni.LiquidazionePensione.View.Web.UserControls.SindacatoPatronato.UCPatronato ucPatronato;
        
        /// <summary>
        /// btnSalva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSalva;
        
        /// <summary>
        /// btnTornaPosizioni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnTornaPosizioni;
        
        /// <summary>
        /// btnTornaARicerca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnTornaARicerca;
    }
}
