//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientContext", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.HostIntegration.TI")]
    [System.SerializableAttribute()]
    public partial class ClientContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ConnectionTypes ConnectionUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMSClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMSLTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMSModNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConnectionViableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConversationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPersistentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LUNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibraryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MirrorProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtmaSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PersistentConnectionCorrelatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PersistentConnectionTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReceiveTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteEnvironmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SendTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliasTransactionId {
            get {
                return this.AliasTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasTransactionIdField, value) != true)) {
                    this.AliasTransactionIdField = value;
                    this.RaisePropertyChanged("AliasTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ConnectionTypes ConnectionUsage {
            get {
                return this.ConnectionUsageField;
            }
            set {
                if ((this.ConnectionUsageField.Equals(value) != true)) {
                    this.ConnectionUsageField = value;
                    this.RaisePropertyChanged("ConnectionUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMSClientId {
            get {
                return this.IMSClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IMSClientIdField, value) != true)) {
                    this.IMSClientIdField = value;
                    this.RaisePropertyChanged("IMSClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMSLTerm {
            get {
                return this.IMSLTermField;
            }
            set {
                if ((object.ReferenceEquals(this.IMSLTermField, value) != true)) {
                    this.IMSLTermField = value;
                    this.RaisePropertyChanged("IMSLTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMSModName {
            get {
                return this.IMSModNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IMSModNameField, value) != true)) {
                    this.IMSModNameField = value;
                    this.RaisePropertyChanged("IMSModName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConnectionViable {
            get {
                return this.IsConnectionViableField;
            }
            set {
                if ((this.IsConnectionViableField.Equals(value) != true)) {
                    this.IsConnectionViableField = value;
                    this.RaisePropertyChanged("IsConnectionViable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConversational {
            get {
                return this.IsConversationalField;
            }
            set {
                if ((this.IsConversationalField.Equals(value) != true)) {
                    this.IsConversationalField = value;
                    this.RaisePropertyChanged("IsConversational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPersistent {
            get {
                return this.IsPersistentField;
            }
            set {
                if ((this.IsPersistentField.Equals(value) != true)) {
                    this.IsPersistentField = value;
                    this.RaisePropertyChanged("IsPersistent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LUName {
            get {
                return this.LUNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LUNameField, value) != true)) {
                    this.LUNameField = value;
                    this.RaisePropertyChanged("LUName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibraryName {
            get {
                return this.LibraryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LibraryNameField, value) != true)) {
                    this.LibraryNameField = value;
                    this.RaisePropertyChanged("LibraryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MirrorProgramName {
            get {
                return this.MirrorProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MirrorProgramNameField, value) != true)) {
                    this.MirrorProgramNameField = value;
                    this.RaisePropertyChanged("MirrorProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModeName {
            get {
                return this.ModeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeNameField, value) != true)) {
                    this.ModeNameField = value;
                    this.RaisePropertyChanged("ModeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtmaSystemId {
            get {
                return this.OtmaSystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OtmaSystemIdField, value) != true)) {
                    this.OtmaSystemIdField = value;
                    this.RaisePropertyChanged("OtmaSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PersistentConnectionCorrelator {
            get {
                return this.PersistentConnectionCorrelatorField;
            }
            set {
                if ((this.PersistentConnectionCorrelatorField.Equals(value) != true)) {
                    this.PersistentConnectionCorrelatorField = value;
                    this.RaisePropertyChanged("PersistentConnectionCorrelator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersistentConnectionTimeout {
            get {
                return this.PersistentConnectionTimeoutField;
            }
            set {
                if ((this.PersistentConnectionTimeoutField.Equals(value) != true)) {
                    this.PersistentConnectionTimeoutField = value;
                    this.RaisePropertyChanged("PersistentConnectionTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReceiveTimeout {
            get {
                return this.ReceiveTimeoutField;
            }
            set {
                if ((this.ReceiveTimeoutField.Equals(value) != true)) {
                    this.ReceiveTimeoutField = value;
                    this.RaisePropertyChanged("ReceiveTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteEnvironment {
            get {
                return this.RemoteEnvironmentField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteEnvironmentField, value) != true)) {
                    this.RemoteEnvironmentField = value;
                    this.RaisePropertyChanged("RemoteEnvironment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SendTimeout {
            get {
                return this.SendTimeoutField;
            }
            set {
                if ((this.SendTimeoutField.Equals(value) != true)) {
                    this.SendTimeoutField = value;
                    this.RaisePropertyChanged("SendTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceTransactionId {
            get {
                return this.SourceTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTransactionIdField, value) != true)) {
                    this.SourceTransactionIdField = value;
                    this.RaisePropertyChanged("SourceTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionTypes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.HostIntegration.TI")]
    public enum ConnectionTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonPersistent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersistentOpen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersistentUse = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersistentClose = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TI_PCI_R.ILiquidazioneCi/WCFServices/", ConfigurationName="HisLiquidazioneCi.ILiquidazioneCi")]
    public interface ILiquidazioneCi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI05", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI05Response")]
        byte[] CI05(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/GACI", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/GACIResponse")]
        byte[] GACI(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI02", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI02Response")]
        byte[] CI02(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI01", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/CI01Response")]
        byte[] CI01(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/UpdateContextInfo", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/UpdateContextInfoResp" +
            "onse")]
        void UpdateContextInfo(ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/ClosePersistentConnec" +
            "tion", ReplyAction="http://TI_PCI_R.ILiquidazioneCi/WCFServices/ILiquidazioneCi/ClosePersistentConnec" +
            "tionResponse")]
        void ClosePersistentConnection(ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiquidazioneCiChannel : INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ILiquidazioneCi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiquidazioneCiClient : System.ServiceModel.ClientBase<INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ILiquidazioneCi>, INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ILiquidazioneCi {
        
        public LiquidazioneCiClient() {
        }
        
        public LiquidazioneCiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiquidazioneCiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidazioneCiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidazioneCiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] CI05(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            return base.Channel.CI05(INPUT, ref clientContext);
        }
        
        public byte[] GACI(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            return base.Channel.GACI(INPUT, ref clientContext);
        }
        
        public byte[] CI02(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            return base.Channel.CI02(INPUT, ref clientContext);
        }
        
        public byte[] CI01(byte[] INPUT, ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            return base.Channel.CI01(INPUT, ref clientContext);
        }
        
        public void UpdateContextInfo(ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            base.Channel.UpdateContextInfo(ref clientContext);
        }
        
        public void ClosePersistentConnection(ref INPS.Pensioni.LiquidazioneCi.Data.HisLiquidazioneCi.ClientContext clientContext) {
            base.Channel.ClosePersistentConnection(ref clientContext);
        }
    }
}
